USE [NovoRumo]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Daily](
	[DailyID] [int] IDENTITY(1,1) NOT NULL,
	[Filename] [varchar](100) NOT NULL,
	[Status] [bit] NOT NULL,
 CONSTRAINT [PK_Daily] PRIMARY KEY CLUSTERED 
(
	[DailyID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO


SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE spGetDaily
AS
BEGIN
SELECT DailyID, Filename, Status 
  FROM Daily WITH (NOLOCK)
END


SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE spGetDailyById( 
	@DailyID AS INT
)
AS 
BEGIN
SELECT DailyID, Filename, Status 
  FROM Daily WITH (NOLOCK)
 WHERE DailyID = @DailyID
END

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE spInsertDaily(
	@Filename AS VARCHAR(100),
	@Status AS BIT
)
AS
BEGIN
INSERT Daily (Filename, Status) VALUES (@Filename, @Status) 
END

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE spUpdateDaily(
	@DailyID AS INT,
	@Filename AS VARCHAR(100),
	@Status AS BIT
)
AS
BEGIN
UPDATE Daily 
   SET Filename = @Filename,
       Status = @Status 
 WHERE DailyID = @DailyID
END

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE spDeleteDaily(
	@DailyID AS INT
)
AS
BEGIN
DELETE FROM Daily WHERE DailyID = @DailyID
END